import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";
import localFont from "next/font/local";

const meraPro = localFont({
  src: [
    {
      path: "../public/static/fonts/MeraPro.otf",
      weight: "500",
      style: "normal",
    }
  ],
  variable: "--font-mera-pro",
})

import "./globals.css";

// const ibmPlexSans = IBM_Plex_Sans({
//   display: 'swap',
//   subsets: ['latin'],
//   weight: ['500', '600', '700'],
//   variable: '--font-ibm-plex-sans',
// });

const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
});   



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${meraPro.variable}`}>{children}</body>
    </html>
  );
}
